version: '2.1'
services:
  content:
    image: "postgres" # use latest official postgres version
    container_name: content
    env_file:
      - database.env # configure postgres
    volumes:
      - content-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - "5432:5432"
volumes:
  content-data: # named volumes can be managed easier using docker-compose
