version: '2.1'
services:
  app:
    container_name: demo
    image: renestel/demo
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - content
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://content/content
  content:
    image: "postgres" # use latest official postgres version
    container_name: content
    env_file:
      - database.env # configure postgres
    volumes:
      - content-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - "5432:5432"
volumes:
  content-data: # named volumes can be managed easier using docker-compose
